"""
Django settings for docia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

from django.urls import reverse_lazy

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

config = environ.Env()
config.read_env(BASE_DIR / ".env")


TESTING = "pytest" in sys.argv[0] or ("manage.py" in sys.argv[0] and "test" in sys.argv[1])
if TESTING:
    assert config.str("ENV") != "prod", "prod environment cannot be used for testing!"
    print("LOAD TEST ENVIRONMENT VARIABLES! (TESTING=True)")
    config.read_env(BASE_DIR / "test.env", overwrite=True)
    assert "test" == config.str("ENV"), "test.env has not be correctly loaded!"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.str("DJANGO_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.bool("DJANGO_DEBUG")

ALLOWED_HOSTS = config.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])

ENV = config.str("ENV")
IN_CELERY_WORKER_PROCESS = sys.argv and sys.argv[0].endswith("celery") and "worker" in sys.argv

ADMIN_BASE_URL_PATH = config.str("DJANGO_ADMIN_BASE_URL_PATH", default="")

# Application definition

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",  # white noise must be before staticfiles
    "django.contrib.staticfiles",
    # Django DSFR
    "widget_tweaks",
    "dsfr",
    "django.forms",  # django.forms must be after dsfr
    # External apps
    "django_celery_results",
    "mozilla_django_oidc",
    "rest_framework",
    # Internal apps
    "docia",
]

MIDDLEWARE = [
    "docia.logging.RequestMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "docia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "docia.context_processors.settings",
            ],
        },
    },
]

WSGI_APPLICATION = "docia.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": config.db("DATABASE_URL"),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Email
DEFAULT_FROM_EMAIL = config.str("DEFAULT_FROM_EMAIL")
EMAIL_BACKEND = config.str("EMAIL_BACKEND")
EMAIL_HOST = config.str("SMTP_HOST", None)
EMAIL_PORT = config.int("SMTP_PORT", None)
EMAIL_HOST_USER = config.str("SMTP_USERNAME", None)
EMAIL_HOST_PASSWORD = config.str("SMTP_PASSWORD", None)
EMAIL_USE_TLS = True


AUTH_USER_MODEL = "docia.User"
AUTHENTICATION_BACKENDS = [
    "docia.auth.backends.CustomOIDCBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = reverse_lazy("login")
OIDC_RP_CLIENT_ID = config.str("OIDC_RP_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = config.str("OIDC_RP_CLIENT_SECRET")
OIDC_OP_DOMAIN = config.str("OIDC_RP_DOMAIN")
OIDC_OP_BASE_URL = f"https://{OIDC_OP_DOMAIN}/api/v2/"
OIDC_OP_AUTHORIZATION_ENDPOINT = OIDC_OP_BASE_URL + "authorize"
OIDC_OP_TOKEN_ENDPOINT = OIDC_OP_BASE_URL + "token"
OIDC_OP_USER_ENDPOINT = OIDC_OP_BASE_URL + "userinfo"
OIDC_OP_JWKS_ENDPOINT = OIDC_OP_BASE_URL + "jwks"
OIDC_CALLBACK_CLASS = "docia.auth.views.CustomOIDCAuthenticationCallbackView"
OIDC_CREATE_USER = True
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email given_name usual_name"
# Specific to lasuite.oidc
OIDC_OP_LOGOUT_ENDPOINT = OIDC_OP_BASE_URL + "session/end"
OIDC_ALLOW_DUPLICATE_EMAILS = False
OIDC_USERINFO_FULLNAME_FIELDS = ["given_name", "usual_name"]
OIDC_USERINFO_SHORTNAME_FIELD = "given_name"
OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION = True
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "dist" / "static"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

storage_backend = config.str("STORAGE_BACKEND")
match storage_backend:
    case "s3":
        storage_backend_class = "storages.backends.s3.S3Storage"
    case "fs":
        storage_backend_class = "django.core.files.storage.FileSystemStorage"
    case _:
        raise ValueError(f"Unknown storage backend: {storage_backend}")


STORAGES = {
    "default": {
        "BACKEND": storage_backend_class,
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


if TESTING:
    STORAGES["staticfiles"]["BACKEND"] = "django.contrib.staticfiles.storage.StaticFilesStorage"


if storage_backend == "s3":
    S3_ENDPOINT_URL = config.str("AWS_S3_ENDPOINT_URL")
    S3_REGION_NAME = config.str("AWS_S3_REGION_NAME")
    S3_ACCESS_KEY_ID = config.str("AWS_S3_ACCESS_KEY_ID")
    S3_SECRET_ACCESS_KEY = config.str("AWS_S3_SECRET_ACCESS_KEY")
    S3_BUCKET_NAME = config.str("STORAGE_S3_BUCKET_NAME")
    STORAGES["default"]["OPTIONS"] = {
        "endpoint_url": S3_ENDPOINT_URL,
        "region_name": S3_REGION_NAME,
        "access_key": S3_ACCESS_KEY_ID,
        "secret_key": S3_SECRET_ACCESS_KEY,
        "bucket_name": S3_BUCKET_NAME,
        "file_overwrite": False,
    }
elif storage_backend == "fs":
    STORAGES["default"]["OPTIONS"] = {
        "location": config.str("STORAGE_LOCAL_PATH"),
        "allow_overwrite": False,
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "docia.logging.RequestIdFilter",
        },
        "session_id": {
            "()": "docia.logging.SessionIdFilter",
        },
        "celery_task": {
            "()": "docia.logging.CeleryTaskFilter",
        },
    },
    "formatters": {
        "simple": {
            "format": "[%(asctime)s] %(levelname)s sid=%(session_id)s rid=%(request_id)s %(name)s %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
        },
        "short": {
            "format": "[%(asctime)s] %(levelname)s %(module)s %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
        },
        "celery": {
            "format": "[%(asctime)s] %(levelname)s %(worker_name)s/%(processName)s task=%(task_name)s[%(task_id)s] %(name)s %(message)s",  # noqa: E501
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
        },
    },
    "handlers": {
        "null": {
            "level": "DEBUG",
            "class": "logging.NullHandler",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": config.str("LOG_FORMATTER", default="simple"),
            "filters": ["request_id", "session_id"],
        },
        "celery": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "celery",
            "filters": ["celery_task"],
        },
    },
    "loggers": {
        "gunicorn": {
            "level": "INFO",
        },
        "django.request": {
            "level": "WARNING",
        },
        "django.db": {
            "level": config.str("LOG_LEVEL_DB", default="WARNING"),
        },
        "boto3": {
            "level": config.str("LOG_LEVEL_BOTO3", default="WARNING"),
        },
        "requests": {
            "level": "DEBUG",
        },
        "docia": {
            "level": config.str("LOG_LEVEL", default="INFO"),
        },
        "celery": {
            "level": config.str("LOG_LEVEL", default="INFO"),
        },
        "flower": {
            "level": config.str("LOG_LEVEL_FLOWER", default="INFO"),
        },
        "": {
            "handlers": [],
            "level": "WARNING",
        },
    },
}


if IN_CELERY_WORKER_PROCESS:
    LOGGING["loggers"][""]["handlers"].append("celery")
else:
    LOGGING["loggers"][""]["handlers"].append("console")


SHELL_AUTO_IMPORTS = [
    ("collections", ("Counter",)),
    ("django.db", ("connection",)),
    ("django.db.transaction", ("atomic",)),
    ("django.db.models", "*"),
    ("django.conf", ("settings",)),
    "time",
    "datetime",
    ("pprint", ("pprint",)),
    ("docia", ("tasks", "models")),
    ("docia.file_processing.pipeline.steps.init_documents", ("init_documents_in_folder",)),
    (
        "docia.file_processing.pipeline.pipeline",
        (
            "launch_batch",
            "init_documents_and_launch_batch",
            "cancel_batch",
            "retry_batch_failures",
            "close_and_retry_stuck_batches",
        ),
    ),
    ("docia.file_processing.pipeline.utils", "*"),
]


CELERY_TASK_ALWAYS_EAGER = config.bool("CELERY_ALWAYS_EAGER", False)
if not CELERY_TASK_ALWAYS_EAGER:
    CELERY_BROKER_URL = config.str("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config.str("CELERY_RESULT_BACKEND_URL")
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_RESULT_EXTENDED = True  # include extended information about the tasks in results (name, args, ...)
CELERY_RESULT_EXPIRES = timedelta(days=90)


FORM_RENDERER = "django.forms.renderers.TemplatesSetting"
DSFR_CHECK_DEPRECATED_PARAMS = DEBUG
DSFR_USE_INTEGRITY_CHECKSUMS = False

TCHAP_SUPPORT_CANAL_URL = config.str("TCHAP_SUPPORT_CANAL_URL", default="")


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "NON_FIELD_ERRORS_KEY": "non_field_errors",
}


MATOMO_URL = config.str("MATOMO_URL", default="")

ALBERT_API_KEY = config.str("ALBERT_API_KEY")
ALBERT_BASE_URL = config.str("ALBERT_BASE_URL")
ALBERT_USE_RATE_LIMITER = config.bool("ALBERT_USE_RATE_LIMITER", default=False)
ALBERT_RATE_PER_MINUTE = config.int("ALBERT_RATE_PER_MINUTE", default=100)
