# Generated by Django 5.2.7 on 2025-10-07 16:29

import django.contrib.postgres.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEngagement',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('num_ej', models.CharField(max_length=255, unique=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('descriptif_prestations', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('prestataire', models.CharField(blank=True, max_length=255, null=True)),
                ('administration', models.CharField(blank=True, max_length=255, null=True)),
                ('siret', models.CharField(blank=True, max_length=255, null=True)),
                ('sources_et_conflits', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engagements',
            },
        ),
        migrations.CreateModel(
            name='DataAttachments',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('extension', models.CharField(blank=True, max_length=255, null=True)),
                ('dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_ocr', models.BooleanField(blank=True, null=True)),
                ('nb_mot', models.IntegerField(blank=True, null=True)),
                ('relevant_content', models.TextField(blank=True, null=True)),
                ('is_embedded', models.BooleanField(blank=True, null=True)),
                ('llm_response', models.JSONField(blank=True, null=True)),
                ('json_error', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_type', models.CharField(blank=True, max_length=255, null=True)),
                ('num_ej', models.ForeignKey(blank=True, db_column='num_ej', null=True, on_delete=django.db.models.deletion.PROTECT, to='docia.dataengagement', to_field='num_ej')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='DataBatch',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('num_ej', models.ForeignKey(blank=True, db_column='num_ej', null=True, on_delete=django.db.models.deletion.PROTECT, to='docia.dataengagement', to_field='num_ej')),
            ],
            options={
                'db_table': 'batch',
                'unique_together': {('batch', 'num_ej')},
            },
        ),
    ]
