# Generated by Django 5.2.7 on 2025-10-08 09:26

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0002_dataengagement_dataattachments_databatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCount',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField()),
                ('interval', models.IntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'unique_together': {('key', 'interval')},
            },
        ),
    ]
