# Generated by Django 5.2.7 on 2025-10-08 15:41

import django.contrib.postgres.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0003_ratelimitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProgrammesMinisteriels',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('programme', models.IntegerField(unique=True)),
                ('libelle', models.CharField()),
                ('nom_ministere', models.CharField()),
            ],
            options={
                'db_table': 'programmes_ministeriels',
            },
        ),
        migrations.AlterField(
            model_name='dataattachments',
            name='batch',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataattachments',
            name='dossier',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataattachments',
            name='extension',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataattachments',
            name='filename',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='dataattachments',
            name='hash',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataattachments',
            name='json_error',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataengagement',
            name='administration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataengagement',
            name='num_ej',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dataengagement',
            name='prestataire',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataengagement',
            name='siret',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DataEngagementItems',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('poste_ej', models.CharField()),
                ('num_contrat', models.CharField(blank=True, null=True)),
                ('groupe_marchandise', models.CharField(blank=True, null=True)),
                ('centre_financier', models.CharField(blank=True, null=True)),
                ('num_ej', models.ForeignKey(db_column='num_ej', on_delete=django.db.models.deletion.CASCADE, to='docia.dataengagement', to_field='num_ej')),
            ],
            options={
                'db_table': 'engagements_items',
                'unique_together': {('num_ej', 'poste_ej')},
            },
        ),
    ]
