# Generated by Django 5.2.7 on 2025-10-13 16:34

import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('page_url', models.CharField(blank=True, default='', help_text='URL path or component identifier')),
                ('user_agent', models.TextField(blank=True, default='', help_text="User's browser and device information")),
                ('num_ej', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
