# Generated by Django 5.2.7 on 2025-10-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0006_trackingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataengagementitems',
            name='num_ej',
            field=models.CharField(max_length=20),
        ),
    ]
