# Generated by Django 5.2.7 on 2025-10-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0007_alter_dataengagementitems_num_ej'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataattachments',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='dataattachments',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
