# Generated by Django 5.2.7 on 2025-11-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0008_dataattachments_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataattachments',
            old_name='num_ej',
            new_name='ej',
        ),
        migrations.RenameField(
            model_name='databatch',
            old_name='num_ej',
            new_name='ej',
        ),
        migrations.AlterUniqueTogether(
            name='databatch',
            unique_together={('batch', 'ej')},
        ),
    ]
