# Generated by Django 5.2.7 on 2025-11-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0010_dataattachments_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataAttachments',
            new_name='DataAttachment',
        ),
    ]
