# Generated by Django 5.2.7 on 2025-11-17 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0012_alter_trackingevent_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTextExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileTextExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')])),
                ('error', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docia.batchtextextraction')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docia.dataattachment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
