# Generated by Django 5.2.7 on 2025-11-17 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0012_alter_trackingevent_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(choices=[('TEXT_EXTRACTION', 'Text Extraction'), ('CLASSIFICATION', 'Classification'), ('ANALYZE', 'Analyze')])),
                ('folder', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELED', 'Canceled')])),
                ('celery_task_id', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(choices=[('TEXT_EXTRACTION', 'Text Extraction'), ('CLASSIFICATION', 'Classification'), ('ANALYZE', 'Analyze')])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELED', 'Canceled')])),
                ('error', models.CharField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, max_length=250)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docia.batchjob')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docia.dataattachment')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
