# Generated by Django 5.2.7 on 2025-11-25 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0013_batch_jobs_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdocumentbatch',
            name='target_classifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='processdocumentbatch',
            name='folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
