# Generated by Django 5.2.7 on 2025-11-21 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0013_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeDocumentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='PENDING')),
                ('celery_task_id', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, max_length=1000, null=True, unique=True, upload_to='')),
                ('filename', models.CharField(max_length=1000)),
                ('folder', models.CharField()),
                ('num_ej', models.CharField(max_length=20)),
                ('extension', models.CharField(max_length=10)),
                ('size', models.PositiveIntegerField()),
                ('hash', models.CharField()),
                ('created_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='documentjob',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='documentjob',
            name='document',
        ),
        migrations.CreateModel(
            name='AnalyzeDocumentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='PENDING')),
                ('celery_task_id', models.CharField(blank=True, max_length=250)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_set', related_query_name='job', to='docia.analyzedocumentbatch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docia.dataattachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyzeDocumentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_type', models.CharField(choices=[('TEXT_EXTRACTION', 'Text Extraction'), ('CLASSIFICATION', 'Classification'), ('INFO_EXTRACTION', 'Info Extraction')])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')])),
                ('error', models.CharField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, max_length=250)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_set', related_query_name='step', to='docia.analyzedocumentjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BatchJob',
        ),
        migrations.DeleteModel(
            name='DocumentJob',
        ),
    ]
