# Generated by Django 5.2.7 on 2025-11-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0014_analyzedocumentbatch_fileinfo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalyzeDocumentBatch',
            new_name='ProcessDocumentBatch',
        ),
        migrations.RenameModel(
            old_name='AnalyzeDocumentJob',
            new_name='ProcessDocumentJob',
        ),
        migrations.RenameModel(
            old_name='AnalyzeDocumentStep',
            new_name='ProcessDocumentStep',
        ),
    ]
