# Generated by Django 5.2.9 on 2025-12-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0014_processdocumentbatch_target_classifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdocumentbatch',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docia.processdocumentbatch'),
        ),
    ]
