# Generated by Django 5.2.9 on 2025-12-18 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0015_processdocumentbatch_retry_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdocumentbatch',
            name='steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TEXT_EXTRACTION', 'Text Extraction'), ('CLASSIFICATION', 'Classification'), ('INFO_EXTRACTION', 'Info Extraction')], max_length=255), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processdocumentstep',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
