# Generated by Django 5.2.9 on 2025-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0016_processdocumentbatch_steps_processdocumentstep_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateGateState',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('next_allowed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
