# Generated by Django 5.2.9 on 2026-01-07 15:16

from django.db import migrations


def _migrate_permissions(old_model, new_model, apps, schema_editor):
    """
    This function migrates all groups with old permissions to the new ones,
    then removes the old permission.
    """
    print()

    # Get the content type for the models
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    ct = ContentType.objects.get(app_label='docia', model=new_model)

    for codename in Permission.objects.filter(content_type=ct, codename__endswith=f"_{old_model}").values_list('codename', flat=True):
        action = codename.split('_')[0]
        old_codename = f'{action}_{old_model}'
        new_codename = f'{action}_{new_model}'

        # Get the permissions
        old_permission = Permission.objects.get(
            content_type=ct,
            codename=old_codename,
        )

        # Get the new permission
        new_permission, _ = Permission.objects.get_or_create(
            content_type=ct,
            codename=new_codename,
            defaults={"name": f"Can {action} {new_model}"},
        )

        # Get all groups that have the old permission
        groups_with_old_perm = Group.objects.filter(permissions=old_permission)

        # Add the new permission to these groups
        for group in groups_with_old_perm:
            print(f"{old_codename} -> {new_codename}: {group.name}")
            group.permissions.add(new_permission)

        print(f"Delete {old_codename}")
        old_permission.delete()
        print()
    print("Done")


def migrate_permissions(apps, schema_editor):
    _migrate_permissions("dataattachment", "document", apps, schema_editor)
    _migrate_permissions("dataattachments", "document", apps, schema_editor)


def reverse_migrate_permissions(apps, schema_editor):
    _migrate_permissions("document", "dataattachment", apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0017_rategatestate'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_migrate_permissions),
        migrations.RenameModel(
            old_name='DataAttachment',
            new_name='Document',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
        migrations.RunPython(migrate_permissions, migrations.RunPython.noop),
    ]
