# Generated by Django 5.2.9 on 2026-01-13 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


def backfill_llm_response_from_structured_data(apps, schema_editor):
    Document = apps.get_model("docia", "Document")
    # Copy only when llm_response is empty to avoid overwriting any already-populated values.
    Document.objects.filter(llm_response__isnull=True, structured_data__isnull=False).update(
        llm_response=models.F("structured_data")
    )


def rename_step_type_info_extraction_to_content_analysis(apps, schema_editor):
    ProcessDocumentStep = apps.get_model("docia", "ProcessDocumentStep")
    ProcessDocumentStep.objects.filter(step_type="INFO_EXTRACTION").update(step_type="CONTENT_ANALYSIS")


def reverse_rename_step_type_info_extraction_to_content_analysis(apps, schema_editor):
    ProcessDocumentStep = apps.get_model("docia", "ProcessDocumentStep")
    ProcessDocumentStep.objects.filter(step_type="CONTENT_ANALYSIS").update(step_type="INFO_EXTRACTION")


def rename_batch_steps_info_extraction_to_content_analysis(apps, schema_editor):
    ProcessDocumentBatch = apps.get_model("docia", "ProcessDocumentBatch")
    for batch in ProcessDocumentBatch.objects.all().only("id", "steps").iterator():
        if not batch.steps:
            continue
        if "INFO_EXTRACTION" not in batch.steps:
            continue
        batch.steps = ["CONTENT_ANALYSIS" if s == "INFO_EXTRACTION" else s for s in batch.steps]
        batch.save(update_fields=["steps"])


def reverse_rename_batch_steps_info_extraction_to_content_analysis(apps, schema_editor):
    ProcessDocumentBatch = apps.get_model("docia", "ProcessDocumentBatch")
    for batch in ProcessDocumentBatch.objects.all().only("id", "steps").iterator():
        if not batch.steps:
            continue
        if "CONTENT_ANALYSIS" not in batch.steps:
            continue
        batch.steps = ["INFO_EXTRACTION" if s == "CONTENT_ANALYSIS" else s for s in batch.steps]
        batch.save(update_fields=["steps"])


class Migration(migrations.Migration):
    """
    Add structured_data to Document.

    In order to keep old data, first rename the llm_response to structured_data,
    then add a new empty column llm_response, and finally backfill the column llm_response.
    """

    dependencies = [
        ('docia', '0018_rename_dataattachment_document_and_more'),
    ]

    operations = [
        # Rename step_type INFO_EXTRACTION to CONTENT_ANALYSIS
        migrations.AlterField(
            model_name='processdocumentbatch',
            name='steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TEXT_EXTRACTION', 'Text Extraction'), ('CLASSIFICATION', 'Classification'), ('CONTENT_ANALYSIS', 'Content Analysis')], max_length=255), size=None),
        ),
        migrations.RunPython(
            rename_batch_steps_info_extraction_to_content_analysis,
            reverse_rename_batch_steps_info_extraction_to_content_analysis,
        ),
        migrations.AlterField(
            model_name='processdocumentstep',
            name='step_type',
            field=models.CharField(choices=[('TEXT_EXTRACTION', 'Text Extraction'), ('CLASSIFICATION', 'Classification'), ('CONTENT_ANALYSIS', 'Content Analysis')]),
        ),
        migrations.RunPython(
            rename_step_type_info_extraction_to_content_analysis,
            reverse_rename_step_type_info_extraction_to_content_analysis,
        ),

        # Add structured_data
        migrations.RenameField(
            model_name='document',
            old_name='llm_response',
            new_name='structured_data',
        ),
        migrations.AddField(
            model_name='document',
            name='llm_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_llm_response_from_structured_data,
            migrations.RunPython.noop,
        ),
    ]
