# Generated by Django 5.2.9 on 2026-01-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0019_add_document_structured_data_and_rename_infoextraction_to_contentanaltsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='json_error',
        ),
    ]
