# Generated by Django 5.2.9 on 2026-01-27 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('docia', '0020_remove_document_json_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('engagements', models.ManyToManyField(related_name='scopes', related_query_name='scopes', to='docia.dataengagement')),
                ('groups', models.ManyToManyField(blank=True, related_name='scopes', related_query_name='scopes', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
