# Generated by Django 5.2.11 on 2026-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0021_engagementscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='engagements',
            field=models.ManyToManyField(related_name='documents', related_query_name='documents', to='docia.dataengagement'),
        ),
    ]
