# Generated by Django 5.2.11 on 2026-02-09 16:47

from django.db import migrations
from django.db.models import F


def populate_engagements_from_ej(apps, schema_editor):
    """Populate the engagements M2M field from the existing ej FK relationships."""
    Document = apps.get_model('docia', 'Document')
    
    # Get all documents that have a non-null ej relationship
    documents_with_ej = Document.objects.exclude(ej__isnull=True).annotate(ej_uuid=F('ej__id'))
    
    total_documents = documents_with_ej.count()
    print(f"Found {total_documents} documents with ej relationships to migrate")

    i = 0
    # Use iterator for memory efficiency
    for i, doc in enumerate(documents_with_ej.iterator(), 1):
        # Add the engagement from ej FK to the engagements M2M field
        doc.engagements.add(doc.ej_uuid)
        
        # Print progress every 1000 documents
        if i % 1000 == 0:
            print(f"Processed {i} documents")
    
    print(f"Successfully migrated {i} documents")


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0022_document_engagements'),
    ]

    operations = [
        migrations.RunPython(
            populate_engagements_from_ej,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
