# Generated by Django 5.2.11 on 2026-02-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0023_auto_20260209_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='ej',
        ),
    ]
