# Generated by Django 5.2.11 on 2026-02-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0024_remove_document_ej'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='num_ej',
        ),
        migrations.AlterField(
            model_name='document',
            name='dossier',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=1000, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='hash',
            field=models.CharField(unique=True),
        ),
    ]
