# Generated by Django 5.2.11 on 2026-02-26 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0025_remove_fileinfo_num_ej_alter_document_dossier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDocumentMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(unique=True)),
                ('name', models.CharField()),
                ('size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='external_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docia.fileinfo'),
        ),
        migrations.CreateModel(
            name='ExternalLinkDocumentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_external_id', models.CharField()),
                ('order_external_id', models.CharField()),
            ],
            options={
                'unique_together': {('document_external_id', 'order_external_id')},
            },
        ),
    ]
