# Generated by Django 5.2.11 on 2026-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0026_externaldocumentmetadata_fileinfo_external_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementscope',
            options={'verbose_name': 'Périmètre'},
        ),
        migrations.RenameField(
            model_name='engagementscope',
            old_name='name',
            new_name='purchase_organization',
        ),
        migrations.AddField(
            model_name='dataengagement',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementscope',
            name='purchase_group',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='engagementscope',
            unique_together={('purchase_organization', 'purchase_group')},
        ),
    ]
