# Generated by Django 5.2.11 on 2026-03-18 12:46

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0027_alter_engagementscope_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldocumentmetadata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 23, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DownloadDocumentError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField()),
                ('external_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_set', related_query_name='error', to='docia.externaldocumentmetadata', to_field='external_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
