# Generated by Django 5.2.12 on 2026-03-31 13:34

from django.db import migrations, models


def populate_root_external_id(apps, schema_editor):
    """Populate root_external_id field based on parent relationships."""
    FileInfo = apps.get_model('docia', 'FileInfo')
    
    # First pass: set root_external_id for objects without parents
    # These are root objects, so root_external_id = external_id
    root_objects = FileInfo.objects.filter(parent__isnull=True)
    updated_count = root_objects.update(root_external_id=models.F('external_id'))
    print(f"Set root_external_id for {updated_count} root objects")
    
    # Second pass: set root_external_id for objects with parents
    # We need to find the root parent for each object
    child_objects = FileInfo.objects.exclude(parent__isnull=True)
    child_objects = child_objects.select_related("parent__parent__parent__parent")
    total_children = child_objects.count()
    
    if total_children > 0:
        print(f"Processing {total_children} child objects...")
    
    processed = 0
    for obj in child_objects.iterator():
        # Find the root parent by traversing up the parent chain
        current = obj
        while current.parent:
            current = current.parent
        # Set root_external_id to the root's external_id
        obj.root_external_id = current.external_id
        obj.save()
        
        processed += 1
        if processed % 100 == 0:
            print(f"Processed {processed}/{total_children} child objects")
    
    if processed > 0:
        print(f"Successfully migrated root_external_id for {processed} child objects")


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0028_document_analyzed_at_externaldocumentmetadata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='root_external_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_root_external_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
