# Generated by Django 5.2.12 on 2026-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0029_fileinfo_root_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nb_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
