# Generated by Django 5.2.13 on 2026-04-21 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('docia', '0030_document_nb_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_set',
                                            related_query_name='scope', to='auth.group')),
                ('purchase_organization', models.CharField(max_length=255)),
                ('purchase_group', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupscope',
            unique_together={('group', 'purchase_organization', 'purchase_group')},
        ),
    ]
