# Generated by Django 5.2.13 on 2026-04-21 08:42

from django.db import migrations


def migrate_to_groupscope(apps, schema_editor):
    """Migrate from EngagementScope.groups M2M to GroupScope model."""
    EngagementScope = apps.get_model('docia', 'EngagementScope')
    GroupScope = apps.get_model('docia', 'GroupScope')
    
    # Get all engagement scopes that have groups (old M2M relationship)
    scopes_with_groups = EngagementScope.objects.filter(groups__isnull=False).distinct()
    
    for scope in scopes_with_groups:
        # Get all groups associated with this scope through the old M2M
        groups = scope.groups.all()
        
        for group in groups:
            # Create GroupScope record for each group-scope combination
            GroupScope.objects.create(
                group=group,
                purchase_organization=scope.purchase_organization,
                purchase_group=scope.purchase_group
            )


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0031_groupscope'),
    ]

    operations = [
        migrations.RunPython(migrate_to_groupscope, migrations.RunPython.noop),
    ]
