# Generated by Django 5.2.13 on 2026-04-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0032_data_20260421_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementscope',
            name='groups',
        ),
    ]
