# Generated by Django 5.2.13 on 2026-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0033_remove_engagementscope_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementscope',
            options={'verbose_name': 'Périmètre EJ', 'verbose_name_plural': 'Pérmiètres EJ'},
        ),
        migrations.AlterModelOptions(
            name='groupscope',
            options={'verbose_name': 'Périmètre de groupe', 'verbose_name_plural': 'Périmètres de group'},
        ),
        migrations.AlterModelOptions(
            name='dataengagement',
            options={'verbose_name': 'Engagement Juridique', 'verbose_name_plural': 'Engagements Juridique'},
        ),
    ]
