# Generated by Django 5.2.13 on 2026-05-07 13:46

from django.db import migrations


SQL_RENAME_FIELD = """
update docia_document doc
set structured_data = jsonb_set(
    structured_data - 'administration_bénéficiaire',  -- Remove the old key
    '{administration_beneficiaire}',                  -- New key path
    structured_data->'administration_bénéficiaire'    -- Copy the value
)
where classification in ('avenant', 'bon_de_commande','conv_financement')
  and doc.structured_data ? 'administration_bénéficiaire'
"""

REVERSE_SQL_RENAME_FIELD = """
update docia_document doc
set structured_data = jsonb_set(
       structured_data - 'administration_beneficiaire',  -- Remove the old key
       '{administration_bénéficiaire}',                  -- New key path
       structured_data->'administration_beneficiaire'    -- Copy the value
                     )
where classification in ('avenant', 'bon_de_commande','conv_financement')
 and doc.structured_data ? 'administration_beneficiaire' \
"""

class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0034_alter_engagementscope_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(SQL_RENAME_FIELD, REVERSE_SQL_RENAME_FIELD),
    ]
