# Generated by Django 5.2.13 on 2026-05-11 14:31

import django.contrib.postgres.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0035_auto_20260507_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEngagement',
            new_name='Engagement',
        ),
        migrations.RenameModel(
            old_name='DataBatch',
            new_name='EngagementTag',
        ),
        migrations.AlterModelTable(
            name='engagement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='engagementtag',
            table=None,
        ),
        migrations.RenameField(
            model_name='engagementtag',
            old_name='batch',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='engagementtag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='engagementtag',
            name='ej',
            field=models.ForeignKey(blank=True, db_column='num_ej', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='tag_set',
                                    related_query_name='tag', to='docia.engagement', to_field='num_ej'),
        ),
        migrations.AlterUniqueTogether(
            name='engagementtag',
            unique_together={('name', 'ej')},
        ),
    ]
