# Generated by Django 5.2.13 on 2026-05-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0036_alter_engagement_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analyze_completion_tokens_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='analyze_prompt_tokens_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='classification_completion_tokens_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='classification_prompt_tokens_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text_tokens_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
