# Generated by Django 5.2.13 on 2026-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0037_document_analyze_completion_tokens_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='external_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
