# Generated by Django 5.2.13 on 2026-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0038_engagement_external_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analyze_model',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='classification_model',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_model',
            field=models.CharField(blank=True, null=True),
        ),
    ]
