# Generated by Django 5.2.13 on 2026-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docia', '0039_document_analyze_model_document_classification_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='created_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
